events {}

http {
    server {
        listen 80;

        location /geomap/ {
            proxy_pass http://geomap-webapp/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /admin/ {
            proxy_pass http://geomap-backend:8010;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://geomap-backend:8010;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/ {
            proxy_pass http://geomap-backend:8010;
            proxy_set_header Host $host;
        }

        location /geomap-media/ {
            proxy_pass http://geomap-minio:9000/geomap-media/;
            proxy_set_header Host $host;
        }
    }
}