# Generated by Django 6.0.1 on 2026-08-02 16:40

"""Миграция схемы данных серверной части GeoMap."""

import django_minio_backend.models
import points.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    """Описывает операции миграции базы данных."""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('photo', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geomap-media'), upload_to=points.models.photo_path, verbose_name='Фото')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram ID автора')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'db_table': 'points',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['is_active'], name='points_is_acti_63c14c_idx'), models.Index(fields=['telegram_user_id'], name='points_telegra_81bed1_idx')],
            },
        ),
    ]
